-- Add role column to User table if it doesn't exist
ALTER TABLE "User" ADD COLUMN "role" TEXT NOT NULL DEFAULT 'user';

-- Insert admin user with autogenerated password
INSERT INTO "User" (id, email, name, password, role, "createdAt")
VALUES (
  gen_random_uuid(),
  'admin@nextup.local',
  'Admin User',
  '$2a$10$x6KXn.JVfENqaKgo398WKO9xXLrubhBTSFRx2YuNss/4rCgmvT1Ja',
  'admin',
  CURRENT_TIMESTAMP
) ON CONFLICT (email) DO NOTHING;
